mode: parallel
containers:
  - address: http://192.168.31.233:5700
    username: admin
    password: admin
    weigth:  
    mode: parallel
    limit: 9999
theme:  
static: ./static
master: 
database:
JDCAddress: #JDC 地址
ApiToken: # xdd api token
qywx_key:
daily_push:
resident:
user_agent:
telegram_bot_token:
telegram_user_id:
qquid:
qqgid:
qbot_public_mode: true
default_priority:
no_ghproxy: false
daily_asset_push_cron: 5 20 * * *
repos:
  - git: https://github.com/yangzhicong/scripts.git
